#ifndef MLIBC_ABIS_MLIBC_XATTR_H
#define MLIBC_ABIS_MLIBC_XATTR_H

enum {
	XATTR_CREATE,
#define XATTR_CREATE XATTR_CREATE
	XATTR_REPLACE
#define XATTR_REPLACE XATTR_REPLACE
};

#endif /* MLIBC_ABIS_MLIBC_XATTR_H */
