#ifndef _SYS_SYSCALL_H
#define _SYS_SYSCALL_H

/* On GNU/Linux, this header provides includes __NR_-prefixed syscall numbers,
 * and their SYS_ aliases. We defer to kernel headers for the numbers (or a
 * stub when building, autogenerated from kernel headers, and a file containing
 * SYS_ defines.
 */
#include <asm/unistd.h>
#include <abi-bits/arch-syscall.h>
#if __has_include(<asm/unistd.h>)
#include <asm/unistd.h>
#endif

#endif /* _SYS_SYSCALL_H */
